//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram")]

namespace UPM.IoT_DSL_AF2
{
	/// <summary>
	/// DomainClass IoT_DSL_AF2Diagram
	/// Description for UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram.DisplayName", typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel), "UPM.IoT_DSL_AF2.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram.Description", typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel), "UPM.IoT_DSL_AF2.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("3383871b-5d29-4201-93b9-21419dd01e2e")]
	public partial class IoT_DSL_AF2Diagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM.IoT_DSL_AF2.Drone)
			{
				global::UPM.IoT_DSL_AF2.DroneImageShape newShape = new global::UPM.IoT_DSL_AF2.DroneImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Accelerometer)
			{
				global::UPM.IoT_DSL_AF2.AccelerometerImageShape newShape = new global::UPM.IoT_DSL_AF2.AccelerometerImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.AirQuality)
			{
				global::UPM.IoT_DSL_AF2.AirQualityImageShape newShape = new global::UPM.IoT_DSL_AF2.AirQualityImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.GPS)
			{
				global::UPM.IoT_DSL_AF2.GPSImageShape newShape = new global::UPM.IoT_DSL_AF2.GPSImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Bus)
			{
				global::UPM.IoT_DSL_AF2.BusImageShape newShape = new global::UPM.IoT_DSL_AF2.BusImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Controller)
			{
				global::UPM.IoT_DSL_AF2.ControllerImageShape newShape = new global::UPM.IoT_DSL_AF2.ControllerImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Sensor)
			{
				global::UPM.IoT_DSL_AF2.SensorImageShape newShape = new global::UPM.IoT_DSL_AF2.SensorImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Actuator)
			{
				global::UPM.IoT_DSL_AF2.ActuatorImageShape newShape = new global::UPM.IoT_DSL_AF2.ActuatorImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Action)
			{
				global::UPM.IoT_DSL_AF2.ActionImageShape newShape = new global::UPM.IoT_DSL_AF2.ActionImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Alarm)
			{
				global::UPM.IoT_DSL_AF2.AlarmImageShape newShape = new global::UPM.IoT_DSL_AF2.AlarmImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.IoTDevice)
			{
				global::UPM.IoT_DSL_AF2.IoTDeviceShape newShape = new global::UPM.IoT_DSL_AF2.IoTDeviceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Measurement)
			{
				global::UPM.IoT_DSL_AF2.MeasuremetShape newShape = new global::UPM.IoT_DSL_AF2.MeasuremetShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.ActuatorPerformsAction)
			{
				global::UPM.IoT_DSL_AF2.ActuatorPerformsActionConnector newShape = new global::UPM.IoT_DSL_AF2.ActuatorPerformsActionConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.ControllerMonitorsSensor)
			{
				global::UPM.IoT_DSL_AF2.ControllerMonitorsSensorConnector newShape = new global::UPM.IoT_DSL_AF2.ControllerMonitorsSensorConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.SensorMonitorsMesurement)
			{
				global::UPM.IoT_DSL_AF2.SensorMonitorsMeasurementConnector newShape = new global::UPM.IoT_DSL_AF2.SensorMonitorsMeasurementConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.ControllerMonitorsActuator)
			{
				global::UPM.IoT_DSL_AF2.ControllerMonitorsActuatorConnector newShape = new global::UPM.IoT_DSL_AF2.ControllerMonitorsActuatorConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.Values)
			{
				global::UPM.IoT_DSL_AF2.ValueImageShape newShape = new global::UPM.IoT_DSL_AF2.ValueImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM.IoT_DSL_AF2.ControllerTriggersAlarm)
			{
				global::UPM.IoT_DSL_AF2.ControllerTriggersAlarmConnector newShape = new global::UPM.IoT_DSL_AF2.ControllerTriggersAlarmConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM.IoT_DSL_AF2.IoTDeviceShape.DecoratorsInitialized += IoTDeviceShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.ControllerImageShape.DecoratorsInitialized += ControllerImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.SensorImageShape.DecoratorsInitialized += SensorImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.ActuatorImageShape.DecoratorsInitialized += ActuatorImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.ActionImageShape.DecoratorsInitialized += ActionImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.AlarmImageShape.DecoratorsInitialized += AlarmImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.ValueImageShape.DecoratorsInitialized += ValueImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.MeasuremetShape.DecoratorsInitialized += MeasuremetShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.DroneImageShape.DecoratorsInitialized += DroneImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.BusImageShape.DecoratorsInitialized += BusImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.GPSImageShape.DecoratorsInitialized += GPSImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.AirQualityImageShape.DecoratorsInitialized += AirQualityImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM.IoT_DSL_AF2.AccelerometerImageShape.DecoratorsInitialized += AccelerometerImageShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for IoTDeviceShape.
		/// </summary>
		internal static partial class IoTDeviceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for IoTDeviceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.LocationDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Location").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ControllerImageShape.
		/// </summary>
		internal static partial class ControllerImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ControllerImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Controller.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for SensorImageShape.
		/// </summary>
		internal static partial class SensorImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for SensorImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Sensor.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ActuatorImageShape.
		/// </summary>
		internal static partial class ActuatorImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ActuatorImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Actuator.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ActionImageShape.
		/// </summary>
		internal static partial class ActionImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ActionImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Action.DescriptionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Description").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Action.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AlarmImageShape.
		/// </summary>
		internal static partial class AlarmImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AlarmImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Alarm.AdvertenceDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Advertence").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Alarm.ConditionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Condition").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Alarm.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ValueImageShape.
		/// </summary>
		internal static partial class ValueImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ValueImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Values.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Values.ScaleDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Scale").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MeasuremetShape.
		/// </summary>
		internal static partial class MeasuremetShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MeasuremetShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Measurement.DateDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Date").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Measurement.HourDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Hour").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Measurement.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Measurement.TopicDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Topic").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DroneImageShape.
		/// </summary>
		internal static partial class DroneImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DroneImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.LocationDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Location").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for BusImageShape.
		/// </summary>
		internal static partial class BusImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for BusImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.LocationDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Location").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.IoTDevice.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for GPSImageShape.
		/// </summary>
		internal static partial class GPSImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for GPSImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Sensor.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AirQualityImageShape.
		/// </summary>
		internal static partial class AirQualityImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AirQualityImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Sensor.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AccelerometerImageShape.
		/// </summary>
		internal static partial class AccelerometerImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AccelerometerImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM.IoT_DSL_AF2.Sensor.IdentifierDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Identifier").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM.IoT_DSL_AF2.ControllerMonitorsSensorConnectAction controllerMonitorsSensorConnectAction;
		private global::UPM.IoT_DSL_AF2.SensorMonitorsMeasurementConnectAction sensorMonitorsMeasurementConnectAction;
		private global::UPM.IoT_DSL_AF2.ControllerMonitorsActuatorConnectAction controllerMonitorsActuatorConnectAction;
		private global::UPM.IoT_DSL_AF2.ActuatorPerformsActionConnectAction actuatorPerformsActionConnectAction;
		private global::UPM.IoT_DSL_AF2.ControllerTriggersAlarmConnectAction controllerTriggersAlarmConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper.ControllerMonitorsSensorFilterString))
				{
					if (this.controllerMonitorsSensorConnectAction == null)
					{
						this.controllerMonitorsSensorConnectAction = new global::UPM.IoT_DSL_AF2.ControllerMonitorsSensorConnectAction(this);
						this.controllerMonitorsSensorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.controllerMonitorsSensorConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper.SensorMonitorsMeasurementFilterString))
				{
					if (this.sensorMonitorsMeasurementConnectAction == null)
					{
						this.sensorMonitorsMeasurementConnectAction = new global::UPM.IoT_DSL_AF2.SensorMonitorsMeasurementConnectAction(this);
						this.sensorMonitorsMeasurementConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.sensorMonitorsMeasurementConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper.ControllerMonitorsActuatorFilterString))
				{
					if (this.controllerMonitorsActuatorConnectAction == null)
					{
						this.controllerMonitorsActuatorConnectAction = new global::UPM.IoT_DSL_AF2.ControllerMonitorsActuatorConnectAction(this);
						this.controllerMonitorsActuatorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.controllerMonitorsActuatorConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper.ActuatorPerformsActionFilterString))
				{
					if (this.actuatorPerformsActionConnectAction == null)
					{
						this.actuatorPerformsActionConnectAction = new global::UPM.IoT_DSL_AF2.ActuatorPerformsActionConnectAction(this);
						this.actuatorPerformsActionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.actuatorPerformsActionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper.ControllerTriggersAlarmFilterString))
				{
					if (this.controllerTriggersAlarmConnectAction == null)
					{
						this.controllerTriggersAlarmConnectAction = new global::UPM.IoT_DSL_AF2.ControllerTriggersAlarmConnectAction(this);
						this.controllerTriggersAlarmConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.controllerTriggersAlarmConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.controllerMonitorsSensorConnectAction != null)
					{
						this.controllerMonitorsSensorConnectAction.Dispose();
						this.controllerMonitorsSensorConnectAction = null;
					}
					if(this.sensorMonitorsMeasurementConnectAction != null)
					{
						this.sensorMonitorsMeasurementConnectAction.Dispose();
						this.sensorMonitorsMeasurementConnectAction = null;
					}
					if(this.controllerMonitorsActuatorConnectAction != null)
					{
						this.controllerMonitorsActuatorConnectAction.Dispose();
						this.controllerMonitorsActuatorConnectAction = null;
					}
					if(this.actuatorPerformsActionConnectAction != null)
					{
						this.actuatorPerformsActionConnectAction.Dispose();
						this.actuatorPerformsActionConnectAction = null;
					}
					if(this.controllerTriggersAlarmConnectAction != null)
					{
						this.controllerTriggersAlarmConnectAction.Dispose();
						this.controllerTriggersAlarmConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// IoT_DSL_AF2Diagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x3383871b, 0x5d29, 0x4201, 0x93, 0xb9, 0x21, 0x41, 0x9d, 0xd0, 0x1e, 0x2e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IoT_DSL_AF2Diagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IoT_DSL_AF2Diagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM.IoT_DSL_AF2
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Drone), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Accelerometer), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.AirQuality), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.GPS), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Bus), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerMonitorsActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.SensorMonitorsMesurement), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerMonitorsSensor), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.IoTDevice), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Measurement), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Values), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Alarm), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Action), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Actuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Sensor), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Controller), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ActuatorPerformsAction), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerTriggersAlarm), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Drone)
				{
					parentElement = GetParentForDrone((global::UPM.IoT_DSL_AF2.Drone)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Accelerometer)
				{
					parentElement = GetParentForAccelerometer((global::UPM.IoT_DSL_AF2.Accelerometer)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.AirQuality)
				{
					parentElement = GetParentForAirQuality((global::UPM.IoT_DSL_AF2.AirQuality)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.GPS)
				{
					parentElement = GetParentForGPS((global::UPM.IoT_DSL_AF2.GPS)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Bus)
				{
					parentElement = GetParentForBus((global::UPM.IoT_DSL_AF2.Bus)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.IoTDevice)
				{
					parentElement = GetParentForIoTDevice((global::UPM.IoT_DSL_AF2.IoTDevice)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Measurement)
				{
					parentElement = GetParentForMeasurement((global::UPM.IoT_DSL_AF2.Measurement)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Values)
				{
					parentElement = GetParentForValues((global::UPM.IoT_DSL_AF2.Values)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Alarm)
				{
					parentElement = GetParentForAlarm((global::UPM.IoT_DSL_AF2.Alarm)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Action)
				{
					parentElement = GetParentForAction((global::UPM.IoT_DSL_AF2.Action)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Actuator)
				{
					parentElement = GetParentForActuator((global::UPM.IoT_DSL_AF2.Actuator)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Sensor)
				{
					parentElement = GetParentForSensor((global::UPM.IoT_DSL_AF2.Sensor)childElement);
				} else
				if(childElement is global::UPM.IoT_DSL_AF2.Controller)
				{
					parentElement = GetParentForController((global::UPM.IoT_DSL_AF2.Controller)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForIoTDevice( global::UPM.IoT_DSL_AF2.IoTDevice root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForController( global::UPM.IoT_DSL_AF2.Controller root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForSensor( global::UPM.IoT_DSL_AF2.Sensor root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForActuator( global::UPM.IoT_DSL_AF2.Actuator root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForAction( global::UPM.IoT_DSL_AF2.Action root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForAlarm( global::UPM.IoT_DSL_AF2.Alarm root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForValues( global::UPM.IoT_DSL_AF2.Values root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.Measurement root2 = root.Measurement;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForMeasurement( global::UPM.IoT_DSL_AF2.Measurement root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForDrone( global::UPM.IoT_DSL_AF2.IoTDevice root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForBus( global::UPM.IoT_DSL_AF2.IoTDevice root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForGPS( global::UPM.IoT_DSL_AF2.Sensor root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForAirQuality( global::UPM.IoT_DSL_AF2.Sensor root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model GetParentForAccelerometer( global::UPM.IoT_DSL_AF2.Sensor root )
			{
				// Segments 0 and 1
				global::UPM.IoT_DSL_AF2.IoTDevice root2 = root.IoTDevice;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM.IoT_DSL_AF2.MyIoTDSLAF2Model result = root2.MyIoTDSLAF2Model;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::UPM.IoT_DSL_AF2.MeasurementHasValues)
				{
					global::System.Collections.IEnumerable elements = GetMeasurementForMeasuremetShapeValuekindFromLastLink((global::UPM.IoT_DSL_AF2.MeasurementHasValues)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetMeasurementForMeasuremetShapeValuekindFromLastLink(global::UPM.IoT_DSL_AF2.MeasurementHasValues root)
			{
				// Segment 0
				global::UPM.IoT_DSL_AF2.Measurement result = root.Measurement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetMeasurementForMeasuremetShapeValuekind(global::UPM.IoT_DSL_AF2.Values root)
			{
				// Segments 1 and 0
				global::UPM.IoT_DSL_AF2.Measurement result = root.Measurement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::UPM.IoT_DSL_AF2.MeasurementHasValues)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekindFromLastLink((global::UPM.IoT_DSL_AF2.MeasurementHasValues)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Values), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::UPM.IoT_DSL_AF2.Values && e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.Values.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekind((global::UPM.IoT_DSL_AF2.Values)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekindFromLastLink((global::UPM.IoT_DSL_AF2.Values)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM.IoT_DSL_AF2.MeasuremetShape compartmentShape = pel as global::UPM.IoT_DSL_AF2.MeasuremetShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekindFromLastLink((global::UPM.IoT_DSL_AF2.MeasurementHasValues)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekind((global::UPM.IoT_DSL_AF2.Values)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::UPM.IoT_DSL_AF2.MeasurementHasValues).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetMeasurementForMeasuremetShapeValuekind((global::UPM.IoT_DSL_AF2.Values)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM.IoT_DSL_AF2.MeasuremetShape), "Valuekind", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Controller), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Sensor), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Actuator), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.Alarm), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.IoTDevice), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.Controller.IdentifierDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.ControllerImageShape.FindControllerImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Controller.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.Sensor.IdentifierDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.SensorImageShape.FindSensorImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Sensor.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.GPSImageShape.FindGPSImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.GPS.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.AirQualityImageShape.FindAirQualityImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.AirQuality.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.AccelerometerImageShape.FindAccelerometerImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Accelerometer.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.Actuator.IdentifierDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.ActuatorImageShape.FindActuatorImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Actuator.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.Alarm.ConditionDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.AlarmImageShape.FindAlarmImageShapeDecorator("Condition");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Alarm.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.IoTDevice.IdentifierDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.DroneImageShape.FindDroneImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Drone.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.BusImageShape.FindBusImageShapeDecorator("Identifier");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Bus.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.IoTDevice.LocationDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.DroneImageShape.FindDroneImageShapeDecorator("Location");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Drone.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.BusImageShape.FindBusImageShapeDecorator("Location");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Bus.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM.IoT_DSL_AF2.IoTDevice.NameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM.IoT_DSL_AF2.DroneImageShape.FindDroneImageShapeDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Drone.DomainClassId);
					}
					decorator = global::UPM.IoT_DSL_AF2.BusImageShape.FindBusImageShapeDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM.IoT_DSL_AF2.Bus.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerMonitorsSensor), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.SensorMonitorsMesurement), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerMonitorsActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ActuatorPerformsAction), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM.IoT_DSL_AF2.ControllerTriggersAlarm), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram diagram = linkShape.Diagram as global::UPM.IoT_DSL_AF2.IoT_DSL_AF2Diagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
