//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM.IoT_DSL_AF2
{
	/// <summary>
	/// DomainModel IoT_DSL_AF2DomainModel
	/// Description for UPM.IoT_DSL_AF2.IoT_DSL_AF2
	/// </summary>
	[DslDesign::DisplayNameResource("UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.DisplayName", typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel), "UPM.IoT_DSL_AF2.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.Description", typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel), "UPM.IoT_DSL_AF2.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("9822eef2-b9c3-450c-be52-09b37692143f")]
	public partial class IoT_DSL_AF2DomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// IoT_DSL_AF2DomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x9822eef2, 0xb9c3, 0x450c, 0xbe, 0x52, 0x09, 0xb3, 0x76, 0x92, 0x14, 0x3f);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public IoT_DSL_AF2DomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(MyIoTDSLAF2Model),
				typeof(Controller),
				typeof(IoTDevice),
				typeof(Sensor),
				typeof(Measurement),
				typeof(Actuator),
				typeof(Values),
				typeof(Action),
				typeof(Alarm),
				typeof(Drone),
				typeof(Bus),
				typeof(GPS),
				typeof(AirQuality),
				typeof(Accelerometer),
				typeof(MyIoTDSLAF2ModelHasIoTDevice),
				typeof(IoTDeviceHasController),
				typeof(ControllerMonitorsSensor),
				typeof(IoTDeviceHasSensor),
				typeof(SensorMonitorsMesurement),
				typeof(IoTDeviceHasActuator),
				typeof(ControllerMonitorsActuator),
				typeof(MyIoTDSLAF2ModelHasMeasurement),
				typeof(MeasurementHasValues),
				typeof(MyIoTDSLAF2ModelHasAction),
				typeof(ActuatorPerformsAction),
				typeof(MyIoTDSLAF2ModelHasAlarm),
				typeof(ControllerTriggersAlarm),
				typeof(IoT_DSL_AF2Diagram),
				typeof(ControllerMonitorsSensorConnector),
				typeof(SensorMonitorsMeasurementConnector),
				typeof(ControllerMonitorsActuatorConnector),
				typeof(ActuatorPerformsActionConnector),
				typeof(ControllerTriggersAlarmConnector),
				typeof(IoTDeviceShape),
				typeof(MeasuremetShape),
				typeof(ActuatorImageShape),
				typeof(ValueImageShape),
				typeof(ControllerImageShape),
				typeof(SensorImageShape),
				typeof(ActionImageShape),
				typeof(AlarmImageShape),
				typeof(DroneImageShape),
				typeof(BusImageShape),
				typeof(GPSImageShape),
				typeof(AirQualityImageShape),
				typeof(AccelerometerImageShape),
				typeof(global::UPM.IoT_DSL_AF2.FixUpDiagram),
				typeof(global::UPM.IoT_DSL_AF2.DecoratorPropertyChanged),
				typeof(global::UPM.IoT_DSL_AF2.ConnectorRolePlayerChanged),
				typeof(global::UPM.IoT_DSL_AF2.CompartmentItemAddRule),
				typeof(global::UPM.IoT_DSL_AF2.CompartmentItemDeleteRule),
				typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM.IoT_DSL_AF2.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(MyIoTDSLAF2Model), "Name", MyIoTDSLAF2Model.NameDomainPropertyId, typeof(MyIoTDSLAF2Model.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Controller), "Identifier", Controller.IdentifierDomainPropertyId, typeof(Controller.IdentifierPropertyHandler)),
				new DomainMemberInfo(typeof(IoTDevice), "Identifier", IoTDevice.IdentifierDomainPropertyId, typeof(IoTDevice.IdentifierPropertyHandler)),
				new DomainMemberInfo(typeof(IoTDevice), "Location", IoTDevice.LocationDomainPropertyId, typeof(IoTDevice.LocationPropertyHandler)),
				new DomainMemberInfo(typeof(IoTDevice), "Name", IoTDevice.NameDomainPropertyId, typeof(IoTDevice.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Sensor), "Identifier", Sensor.IdentifierDomainPropertyId, typeof(Sensor.IdentifierPropertyHandler)),
				new DomainMemberInfo(typeof(Measurement), "Topic", Measurement.TopicDomainPropertyId, typeof(Measurement.TopicPropertyHandler)),
				new DomainMemberInfo(typeof(Measurement), "Identifier", Measurement.IdentifierDomainPropertyId, typeof(Measurement.IdentifierPropertyHandler)),
				new DomainMemberInfo(typeof(Measurement), "Date", Measurement.DateDomainPropertyId, typeof(Measurement.DatePropertyHandler)),
				new DomainMemberInfo(typeof(Measurement), "Hour", Measurement.HourDomainPropertyId, typeof(Measurement.HourPropertyHandler)),
				new DomainMemberInfo(typeof(Actuator), "Identifier", Actuator.IdentifierDomainPropertyId, typeof(Actuator.IdentifierPropertyHandler)),
				new DomainMemberInfo(typeof(Values), "Name", Values.NameDomainPropertyId, typeof(Values.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Values), "Scale", Values.ScaleDomainPropertyId, typeof(Values.ScalePropertyHandler)),
				new DomainMemberInfo(typeof(Action), "Name", Action.NameDomainPropertyId, typeof(Action.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Action), "Description", Action.DescriptionDomainPropertyId, typeof(Action.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(Alarm), "Name", Alarm.NameDomainPropertyId, typeof(Alarm.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Alarm), "Condition", Alarm.ConditionDomainPropertyId, typeof(Alarm.ConditionPropertyHandler)),
				new DomainMemberInfo(typeof(Alarm), "Advertence", Alarm.AdvertenceDomainPropertyId, typeof(Alarm.AdvertencePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasIoTDevice), "MyIoTDSLAF2Model", MyIoTDSLAF2ModelHasIoTDevice.MyIoTDSLAF2ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasIoTDevice), "IoTDevice", MyIoTDSLAF2ModelHasIoTDevice.IoTDeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasController), "IoTDevice", IoTDeviceHasController.IoTDeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasController), "Controller", IoTDeviceHasController.ControllerDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerMonitorsSensor), "Controller", ControllerMonitorsSensor.ControllerDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerMonitorsSensor), "Sensor", ControllerMonitorsSensor.SensorDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasSensor), "IoTDevice", IoTDeviceHasSensor.IoTDeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasSensor), "Sensor", IoTDeviceHasSensor.SensorDomainRoleId),
				new DomainRolePlayerInfo(typeof(SensorMonitorsMesurement), "Sensor", SensorMonitorsMesurement.SensorDomainRoleId),
				new DomainRolePlayerInfo(typeof(SensorMonitorsMesurement), "Measurement", SensorMonitorsMesurement.MeasurementDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasActuator), "IoTDevice", IoTDeviceHasActuator.IoTDeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(IoTDeviceHasActuator), "Actuator", IoTDeviceHasActuator.ActuatorDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerMonitorsActuator), "Controller", ControllerMonitorsActuator.ControllerDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerMonitorsActuator), "Actuator", ControllerMonitorsActuator.ActuatorDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasMeasurement), "MyIoTDSLAF2Model", MyIoTDSLAF2ModelHasMeasurement.MyIoTDSLAF2ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasMeasurement), "Measurement", MyIoTDSLAF2ModelHasMeasurement.MeasurementDomainRoleId),
				new DomainRolePlayerInfo(typeof(MeasurementHasValues), "Measurement", MeasurementHasValues.MeasurementDomainRoleId),
				new DomainRolePlayerInfo(typeof(MeasurementHasValues), "Values", MeasurementHasValues.ValuesDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasAction), "MyIoTDSLAF2Model", MyIoTDSLAF2ModelHasAction.MyIoTDSLAF2ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasAction), "Action", MyIoTDSLAF2ModelHasAction.ActionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ActuatorPerformsAction), "Actuator", ActuatorPerformsAction.ActuatorDomainRoleId),
				new DomainRolePlayerInfo(typeof(ActuatorPerformsAction), "Action", ActuatorPerformsAction.ActionDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasAlarm), "MyIoTDSLAF2Model", MyIoTDSLAF2ModelHasAlarm.MyIoTDSLAF2ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MyIoTDSLAF2ModelHasAlarm), "Alarm", MyIoTDSLAF2ModelHasAlarm.AlarmDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerTriggersAlarm), "Controller", ControllerTriggersAlarm.ControllerDomainRoleId),
				new DomainRolePlayerInfo(typeof(ControllerTriggersAlarm), "Alarm", ControllerTriggersAlarm.AlarmDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(33);
				createElementMap.Add(typeof(MyIoTDSLAF2Model), 0);
				createElementMap.Add(typeof(Controller), 1);
				createElementMap.Add(typeof(IoTDevice), 2);
				createElementMap.Add(typeof(Sensor), 3);
				createElementMap.Add(typeof(Measurement), 4);
				createElementMap.Add(typeof(Actuator), 5);
				createElementMap.Add(typeof(Values), 6);
				createElementMap.Add(typeof(Action), 7);
				createElementMap.Add(typeof(Alarm), 8);
				createElementMap.Add(typeof(Drone), 9);
				createElementMap.Add(typeof(Bus), 10);
				createElementMap.Add(typeof(GPS), 11);
				createElementMap.Add(typeof(AirQuality), 12);
				createElementMap.Add(typeof(Accelerometer), 13);
				createElementMap.Add(typeof(IoT_DSL_AF2Diagram), 14);
				createElementMap.Add(typeof(ControllerMonitorsSensorConnector), 15);
				createElementMap.Add(typeof(SensorMonitorsMeasurementConnector), 16);
				createElementMap.Add(typeof(ControllerMonitorsActuatorConnector), 17);
				createElementMap.Add(typeof(ActuatorPerformsActionConnector), 18);
				createElementMap.Add(typeof(ControllerTriggersAlarmConnector), 19);
				createElementMap.Add(typeof(IoTDeviceShape), 20);
				createElementMap.Add(typeof(MeasuremetShape), 21);
				createElementMap.Add(typeof(ActuatorImageShape), 22);
				createElementMap.Add(typeof(ValueImageShape), 23);
				createElementMap.Add(typeof(ControllerImageShape), 24);
				createElementMap.Add(typeof(SensorImageShape), 25);
				createElementMap.Add(typeof(ActionImageShape), 26);
				createElementMap.Add(typeof(AlarmImageShape), 27);
				createElementMap.Add(typeof(DroneImageShape), 28);
				createElementMap.Add(typeof(BusImageShape), 29);
				createElementMap.Add(typeof(GPSImageShape), 30);
				createElementMap.Add(typeof(AirQualityImageShape), 31);
				createElementMap.Add(typeof(AccelerometerImageShape), 32);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new MyIoTDSLAF2Model(partition, propertyAssignments);
				case 1: return new Controller(partition, propertyAssignments);
				case 2: return new IoTDevice(partition, propertyAssignments);
				case 3: return new Sensor(partition, propertyAssignments);
				case 4: return new Measurement(partition, propertyAssignments);
				case 5: return new Actuator(partition, propertyAssignments);
				case 6: return new Values(partition, propertyAssignments);
				case 7: return new Action(partition, propertyAssignments);
				case 8: return new Alarm(partition, propertyAssignments);
				case 9: return new Drone(partition, propertyAssignments);
				case 10: return new Bus(partition, propertyAssignments);
				case 11: return new GPS(partition, propertyAssignments);
				case 12: return new AirQuality(partition, propertyAssignments);
				case 13: return new Accelerometer(partition, propertyAssignments);
				case 14: return new IoT_DSL_AF2Diagram(partition, propertyAssignments);
				case 15: return new ControllerMonitorsSensorConnector(partition, propertyAssignments);
				case 16: return new SensorMonitorsMeasurementConnector(partition, propertyAssignments);
				case 17: return new ControllerMonitorsActuatorConnector(partition, propertyAssignments);
				case 18: return new ActuatorPerformsActionConnector(partition, propertyAssignments);
				case 19: return new ControllerTriggersAlarmConnector(partition, propertyAssignments);
				case 20: return new IoTDeviceShape(partition, propertyAssignments);
				case 21: return new MeasuremetShape(partition, propertyAssignments);
				case 22: return new ActuatorImageShape(partition, propertyAssignments);
				case 23: return new ValueImageShape(partition, propertyAssignments);
				case 24: return new ControllerImageShape(partition, propertyAssignments);
				case 25: return new SensorImageShape(partition, propertyAssignments);
				case 26: return new ActionImageShape(partition, propertyAssignments);
				case 27: return new AlarmImageShape(partition, propertyAssignments);
				case 28: return new DroneImageShape(partition, propertyAssignments);
				case 29: return new BusImageShape(partition, propertyAssignments);
				case 30: return new GPSImageShape(partition, propertyAssignments);
				case 31: return new AirQualityImageShape(partition, propertyAssignments);
				case 32: return new AccelerometerImageShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(13);
				createElementLinkMap.Add(typeof(MyIoTDSLAF2ModelHasIoTDevice), 0);
				createElementLinkMap.Add(typeof(IoTDeviceHasController), 1);
				createElementLinkMap.Add(typeof(ControllerMonitorsSensor), 2);
				createElementLinkMap.Add(typeof(IoTDeviceHasSensor), 3);
				createElementLinkMap.Add(typeof(SensorMonitorsMesurement), 4);
				createElementLinkMap.Add(typeof(IoTDeviceHasActuator), 5);
				createElementLinkMap.Add(typeof(ControllerMonitorsActuator), 6);
				createElementLinkMap.Add(typeof(MyIoTDSLAF2ModelHasMeasurement), 7);
				createElementLinkMap.Add(typeof(MeasurementHasValues), 8);
				createElementLinkMap.Add(typeof(MyIoTDSLAF2ModelHasAction), 9);
				createElementLinkMap.Add(typeof(ActuatorPerformsAction), 10);
				createElementLinkMap.Add(typeof(MyIoTDSLAF2ModelHasAlarm), 11);
				createElementLinkMap.Add(typeof(ControllerTriggersAlarm), 12);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new MyIoTDSLAF2ModelHasIoTDevice(partition, roleAssignments, propertyAssignments);
				case 1: return new IoTDeviceHasController(partition, roleAssignments, propertyAssignments);
				case 2: return new ControllerMonitorsSensor(partition, roleAssignments, propertyAssignments);
				case 3: return new IoTDeviceHasSensor(partition, roleAssignments, propertyAssignments);
				case 4: return new SensorMonitorsMesurement(partition, roleAssignments, propertyAssignments);
				case 5: return new IoTDeviceHasActuator(partition, roleAssignments, propertyAssignments);
				case 6: return new ControllerMonitorsActuator(partition, roleAssignments, propertyAssignments);
				case 7: return new MyIoTDSLAF2ModelHasMeasurement(partition, roleAssignments, propertyAssignments);
				case 8: return new MeasurementHasValues(partition, roleAssignments, propertyAssignments);
				case 9: return new MyIoTDSLAF2ModelHasAction(partition, roleAssignments, propertyAssignments);
				case 10: return new ActuatorPerformsAction(partition, roleAssignments, propertyAssignments);
				case 11: return new MyIoTDSLAF2ModelHasAlarm(partition, roleAssignments, propertyAssignments);
				case 12: return new ControllerTriggersAlarm(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM.IoT_DSL_AF2.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return IoT_DSL_AF2DomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (IoT_DSL_AF2DomainModel.resourceManager == null)
				{
					IoT_DSL_AF2DomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(IoT_DSL_AF2DomainModel).Assembly);
				}
				return IoT_DSL_AF2DomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return IoT_DSL_AF2DomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return IoT_DSL_AF2DomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IoT_DSL_AF2DomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new IoT_DSL_AF2CopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					IoT_DSL_AF2DomainModel.copyClosure = copyFilter;
				}
				return IoT_DSL_AF2DomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IoT_DSL_AF2DomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new IoT_DSL_AF2DeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					IoT_DSL_AF2DomainModel.removeClosure = removeFilter;
				}
				return IoT_DSL_AF2DomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM.IoT_DSL_AF2.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IoT_DSL_AF2DeleteClosure : IoT_DSL_AF2DeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IoT_DSL_AF2DeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IoT_DSL_AF2DeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public IoT_DSL_AF2DeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.MyIoTDSLAF2ModelHasIoTDevice.IoTDeviceDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.IoTDeviceHasController.ControllerDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.IoTDeviceHasSensor.SensorDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.IoTDeviceHasActuator.ActuatorDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.MyIoTDSLAF2ModelHasMeasurement.MeasurementDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.MeasurementHasValues.ValuesDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.MyIoTDSLAF2ModelHasAction.ActionDomainRoleId, true);
			DomainRoles.Add(global::UPM.IoT_DSL_AF2.MyIoTDSLAF2ModelHasAlarm.AlarmDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IoT_DSL_AF2CopyClosure : IoT_DSL_AF2CopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IoT_DSL_AF2CopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IoT_DSL_AF2CopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IoT_DSL_AF2CopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

