//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace UPM.IoT_DSL_AF2
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class IoT_DSL_AF2ToolboxHelper : IoT_DSL_AF2ToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new IoT_DSL_AF2ToolboxHelper.
		/// </summary>
		public IoT_DSL_AF2ToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class IoT_DSL_AF2ToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify IoT_DSL_AF2 toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "IoT_DSL_AF2.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ControllerMonitorsSensor connector tool.
		/// </summary>
		public const string ControllerMonitorsSensorFilterString = "ControllerMonitorsSensor.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify SensorMonitorsMeasurement connector tool.
		/// </summary>
		public const string SensorMonitorsMeasurementFilterString = "SensorMonitorsMeasurement.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ControllerMonitorsActuator connector tool.
		/// </summary>
		public const string ControllerMonitorsActuatorFilterString = "ControllerMonitorsActuator.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ActuatorPerformsAction connector tool.
		/// </summary>
		public const string ActuatorPerformsActionFilterString = "ActuatorPerformsAction.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ControllerTriggersAlarm connector tool.
		/// </summary>
		public const string ControllerTriggersAlarmFilterString = "ControllerTriggersAlarm.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new IoT_DSL_AF2ToolboxHelperBase.
		/// </summary>
		protected IoT_DSL_AF2ToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.SingletonResourceManager.GetString("IoT_DSL_AF2ToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 18;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "UPM.IoT_DSL_AF2.IoTDeviceToolboxItem":
					// Add IoTDevice shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.IoTDeviceToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IoTDeviceToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IoTDeviceToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IoTDevice", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IoTDeviceToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.IoTDevice.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.ControllerToolboxItem":
					// Add Controller shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ControllerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControllerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControllerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Controller", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControllerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Controller.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.SensorToolboxItem":
					// Add Sensor shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.SensorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SensorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SensorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Sensor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SensorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Sensor.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.ControllerMonitorsSensorToolboxItem":

					// Add ControllerMonitorsSensor connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ControllerMonitorsSensorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControllerMonitorsSensorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControllerMonitorsSensorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ControllerMonitorsSensor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControllerMonitorsSensorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ControllerMonitorsSensorFilterString)
						});
					break;
				case "UPM.IoT_DSL_AF2.MeasurementToolboxItem":
					// Add Measurement shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.MeasurementToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("MeasurementToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("MeasurementToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Measurement", // F1 help keyword for the toolbox item.
						resourceManager.GetString("MeasurementToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Measurement.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.SensorMonitorsMeasurementToolboxItem":

					// Add SensorMonitorsMeasurement connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.SensorMonitorsMeasurementToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SensorMonitorsMeasurementToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SensorMonitorsMeasurementToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SensorMonitorsMeasurement", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SensorMonitorsMeasurementToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(SensorMonitorsMeasurementFilterString)
						});
					break;
				case "UPM.IoT_DSL_AF2.ActuatorToolboxItem":
					// Add Actuator shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ActuatorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ActuatorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ActuatorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Actuator", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ActuatorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Actuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.ControllerMonitorsActuatorToolboxItem":

					// Add ControllerMonitorsActuator connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ControllerMonitorsActuatorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControllerMonitorsActuatorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControllerMonitorsActuatorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ControllerMonitorsActuator", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControllerMonitorsActuatorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ControllerMonitorsActuatorFilterString)
						});
					break;
				case "UPM.IoT_DSL_AF2.ValuesToolboxItem":
					// Add Values shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ValuesToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ValuesToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ValuesToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Values", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ValuesToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Values.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.ActuatorPerformsActionToolboxItem":

					// Add ActuatorPerformsAction connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ActuatorPerformsActionToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ActuatorPerformsActionToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ActuatorPerformsActionToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ActuatorPerformsAction", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ActuatorPerformsActionToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ActuatorPerformsActionFilterString)
						});
					break;
				case "UPM.IoT_DSL_AF2.ActionToolboxItem":
					// Add Action shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ActionToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ActionToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ActionToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Action", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ActionToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Action.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.AlarmToolboxItem":
					// Add Alarm shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.AlarmToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AlarmToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AlarmToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Alarm", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AlarmToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Alarm.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.ControllerTriggersAlarmToolboxItem":

					// Add ControllerTriggersAlarm connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.ControllerTriggersAlarmToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControllerTriggersAlarmToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControllerTriggersAlarmToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ControllerTriggersAlarm", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControllerTriggersAlarmToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ControllerTriggersAlarmFilterString)
						});
					break;
				case "UPM.IoT_DSL_AF2.DroneToolboxItem":
					// Add Drone shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.DroneToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						14, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DroneToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DroneToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Drone", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DroneToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Drone.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.BusToolboxItem":
					// Add Bus shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.BusToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						15, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BusToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BusToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Bus", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BusToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Bus.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.GPSToolboxItem":
					// Add GPS shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.GPSToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						16, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("GPSToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("GPSToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"GPS", // F1 help keyword for the toolbox item.
						resourceManager.GetString("GPSToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.GPS.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.AirQualitySensorToolboxItem":
					// Add AirQualitySensor shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.AirQualitySensorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						17, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AirQualitySensorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AirQualitySensorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AirQualitySensor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AirQualitySensorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.AirQuality.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM.IoT_DSL_AF2.AccelerometerToolboxItem":
					// Add Accelerometer shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM.IoT_DSL_AF2.AccelerometerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						18, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AccelerometerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AccelerometerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("IoT_DSL_AF2ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Accelerometer", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AccelerometerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM.IoT_DSL_AF2.Accelerometer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
