//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM.IoT_DSL_AF2
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "af2";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"IoT_DSL_AF2";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID IoT_DSL_AF2DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IoT_DSL_AF2CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID IoT_DSL_AF2ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IoT_DSL_AF2CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewIoT_DSL_AF2ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IoT_DSL_AF2CommandSetId), 0x0001);
	
		// Package identifier
		public const string IoT_DSL_AF2PackageId = "f623f501-a65e-4495-b5e8-9402207bc9a9";
		
		// Editor factory identifier
		public const string IoT_DSL_AF2EditorFactoryId = "2afb84dc-19c8-436e-b377-622d9cf87eef";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string IoT_DSL_AF2ModelExplorerToolWindowId = "0e2d23c4-b9a3-420b-a998-be39e66efb18";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM.IoT_DSL_AF2
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string IoT_DSL_AF2CommandSetId = "3d9d9334-9645-42c6-9d4d-663d528b0a74";
	}
}