//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace UPM.IoT_DSL_AF2
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\14.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(IoT_DSL_AF2ExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(IoT_DSL_AF2ExplorerToolWindow), Constants.IoT_DSL_AF2EditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@IoT_DSL_AF2ToolboxTab;UPM.IoT_DSL_AF2.Dsl.dll", "UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@IoTDeviceToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.IoTDeviceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IoTDevice", 
					"@IoTDeviceToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ControllerToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ControllerToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Controller", 
					"@ControllerToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@SensorToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.SensorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Sensor", 
					"@SensorToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ControllerMonitorsSensorToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ControllerMonitorsSensorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ControllerMonitorsSensor", 
					"@ControllerMonitorsSensorToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@MeasurementToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.MeasurementToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Measurement", 
					"@MeasurementToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@SensorMonitorsMeasurementToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.SensorMonitorsMeasurementToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SensorMonitorsMeasurement", 
					"@SensorMonitorsMeasurementToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ActuatorToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ActuatorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Actuator", 
					"@ActuatorToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ControllerMonitorsActuatorToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ControllerMonitorsActuatorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ControllerMonitorsActuator", 
					"@ControllerMonitorsActuatorToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ValuesToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ValuesToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Values", 
					"@ValuesToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ActuatorPerformsActionToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ActuatorPerformsActionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ActuatorPerformsAction", 
					"@ActuatorPerformsActionToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ActionToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ActionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Action", 
					"@ActionToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@AlarmToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.AlarmToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Alarm", 
					"@AlarmToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@ControllerTriggersAlarmToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.ControllerTriggersAlarmToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ControllerTriggersAlarm", 
					"@ControllerTriggersAlarmToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@DroneToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.DroneToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Drone", 
					"@DroneToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@BusToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.BusToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Bus", 
					"@BusToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@GPSToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.GPSToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"GPS", 
					"@GPSToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@AirQualitySensorToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.AirQualitySensorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AirQualitySensor", 
					"@AirQualitySensorToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideStaticToolboxItem("UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxTab",
					"@AccelerometerToolboxItem;UPM.IoT_DSL_AF2.Dsl.dll", 
					"UPM.IoT_DSL_AF2.AccelerometerToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Accelerometer", 
					"@AccelerometerToolboxBitmap;UPM.IoT_DSL_AF2.Dsl.dll", 
					0xff00ff,
					Index = 17)]
	[VSShell::ProvideEditorFactory(typeof(IoT_DSL_AF2EditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(IoT_DSL_AF2EditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(IoT_DSL_AF2EditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"IoT_DSL_AF2", typeof(IoT_DSL_AF2EditorFactory))]

	internal abstract partial class IoT_DSL_AF2PackageBase : DslShell::ModelingPackage
	{
		protected global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new IoT_DSL_AF2EditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM.IoT_DSL_AF2.IoT_DSL_AF2ToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			IoT_DSL_AF2CommandSet commandSet = new IoT_DSL_AF2CommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			IoT_DSL_AF2ClipboardCommandSet clipboardCommandSet = new IoT_DSL_AF2ClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(IoT_DSL_AF2ExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM.IoT_DSL_AF2
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DirectiveProcessor), global::UPM.IoT_DSL_AF2.IoT_DSL_AF2DirectiveProcessor.IoT_DSL_AF2DirectiveProcessorName, "A directive processor that provides access to IoT_DSL_AF2 files")]
	[global::System.Runtime.InteropServices.Guid(Constants.IoT_DSL_AF2PackageId)]
	internal sealed partial class IoT_DSL_AF2Package : IoT_DSL_AF2PackageBase
	{
	}
}